package com.trm.models;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c-id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c-name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c-identity
     *
     * @mbg.generated
     */
    private String cIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c-phone
     *
     * @mbg.generated
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c-id
     *
     * @return the value of customer.c-id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c-id
     *
     * @param cId the value for customer.c-id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c-name
     *
     * @return the value of customer.c-name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c-name
     *
     * @param cName the value for customer.c-name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c-identity
     *
     * @return the value of customer.c-identity
     *
     * @mbg.generated
     */
    public String getcIdentity() {
        return cIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c-identity
     *
     * @param cIdentity the value for customer.c-identity
     *
     * @mbg.generated
     */
    public void setcIdentity(String cIdentity) {
        this.cIdentity = cIdentity == null ? null : cIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c-phone
     *
     * @return the value of customer.c-phone
     *
     * @mbg.generated
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c-phone
     *
     * @param cPhone the value for customer.c-phone
     *
     * @mbg.generated
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cId=").append(cId);
        sb.append(", cName=").append(cName);
        sb.append(", cIdentity=").append(cIdentity);
        sb.append(", cPhone=").append(cPhone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}