package com.trm.models;

import java.io.Serializable;

public class Details implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.s-id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.d-route
     *
     * @mbg.generated
     */
    private String dRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.d-stay
     *
     * @mbg.generated
     */
    private String dStay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.d-meal
     *
     * @mbg.generated
     */
    private String dMeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.d-tool
     *
     * @mbg.generated
     */
    private String dTool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.d-brief
     *
     * @mbg.generated
     */
    private String dBrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.d-days
     *
     * @mbg.generated
     */
    private Integer dDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table details
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.s-id
     *
     * @return the value of details.s-id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.s-id
     *
     * @param sId the value for details.s-id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.d-route
     *
     * @return the value of details.d-route
     *
     * @mbg.generated
     */
    public String getdRoute() {
        return dRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.d-route
     *
     * @param dRoute the value for details.d-route
     *
     * @mbg.generated
     */
    public void setdRoute(String dRoute) {
        this.dRoute = dRoute == null ? null : dRoute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.d-stay
     *
     * @return the value of details.d-stay
     *
     * @mbg.generated
     */
    public String getdStay() {
        return dStay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.d-stay
     *
     * @param dStay the value for details.d-stay
     *
     * @mbg.generated
     */
    public void setdStay(String dStay) {
        this.dStay = dStay == null ? null : dStay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.d-meal
     *
     * @return the value of details.d-meal
     *
     * @mbg.generated
     */
    public String getdMeal() {
        return dMeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.d-meal
     *
     * @param dMeal the value for details.d-meal
     *
     * @mbg.generated
     */
    public void setdMeal(String dMeal) {
        this.dMeal = dMeal == null ? null : dMeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.d-tool
     *
     * @return the value of details.d-tool
     *
     * @mbg.generated
     */
    public String getdTool() {
        return dTool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.d-tool
     *
     * @param dTool the value for details.d-tool
     *
     * @mbg.generated
     */
    public void setdTool(String dTool) {
        this.dTool = dTool == null ? null : dTool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.d-brief
     *
     * @return the value of details.d-brief
     *
     * @mbg.generated
     */
    public String getdBrief() {
        return dBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.d-brief
     *
     * @param dBrief the value for details.d-brief
     *
     * @mbg.generated
     */
    public void setdBrief(String dBrief) {
        this.dBrief = dBrief == null ? null : dBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.d-days
     *
     * @return the value of details.d-days
     *
     * @mbg.generated
     */
    public Integer getdDays() {
        return dDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.d-days
     *
     * @param dDays the value for details.d-days
     *
     * @mbg.generated
     */
    public void setdDays(Integer dDays) {
        this.dDays = dDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sId=").append(sId);
        sb.append(", dRoute=").append(dRoute);
        sb.append(", dStay=").append(dStay);
        sb.append(", dMeal=").append(dMeal);
        sb.append(", dTool=").append(dTool);
        sb.append(", dBrief=").append(dBrief);
        sb.append(", dDays=").append(dDays);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}