package com.trm.models;

import java.io.Serializable;

public class Hotel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h-id
     *
     * @mbg.generated
     */
    private Integer hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h-position
     *
     * @mbg.generated
     */
    private String hPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h-price
     *
     * @mbg.generated
     */
    private String hPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h-name
     *
     * @mbg.generated
     */
    private String hName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h-introduce
     *
     * @mbg.generated
     */
    private String hIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h-star
     *
     * @mbg.generated
     */
    private Integer hStar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h-id
     *
     * @return the value of hotel.h-id
     *
     * @mbg.generated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h-id
     *
     * @param hId the value for hotel.h-id
     *
     * @mbg.generated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h-position
     *
     * @return the value of hotel.h-position
     *
     * @mbg.generated
     */
    public String gethPosition() {
        return hPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h-position
     *
     * @param hPosition the value for hotel.h-position
     *
     * @mbg.generated
     */
    public void sethPosition(String hPosition) {
        this.hPosition = hPosition == null ? null : hPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h-price
     *
     * @return the value of hotel.h-price
     *
     * @mbg.generated
     */
    public String gethPrice() {
        return hPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h-price
     *
     * @param hPrice the value for hotel.h-price
     *
     * @mbg.generated
     */
    public void sethPrice(String hPrice) {
        this.hPrice = hPrice == null ? null : hPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h-name
     *
     * @return the value of hotel.h-name
     *
     * @mbg.generated
     */
    public String gethName() {
        return hName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h-name
     *
     * @param hName the value for hotel.h-name
     *
     * @mbg.generated
     */
    public void sethName(String hName) {
        this.hName = hName == null ? null : hName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h-introduce
     *
     * @return the value of hotel.h-introduce
     *
     * @mbg.generated
     */
    public String gethIntroduce() {
        return hIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h-introduce
     *
     * @param hIntroduce the value for hotel.h-introduce
     *
     * @mbg.generated
     */
    public void sethIntroduce(String hIntroduce) {
        this.hIntroduce = hIntroduce == null ? null : hIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h-star
     *
     * @return the value of hotel.h-star
     *
     * @mbg.generated
     */
    public Integer gethStar() {
        return hStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h-star
     *
     * @param hStar the value for hotel.h-star
     *
     * @mbg.generated
     */
    public void sethStar(Integer hStar) {
        this.hStar = hStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hId=").append(hId);
        sb.append(", hPosition=").append(hPosition);
        sb.append(", hPrice=").append(hPrice);
        sb.append(", hName=").append(hName);
        sb.append(", hIntroduce=").append(hIntroduce);
        sb.append(", hStar=").append(hStar);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}