package com.trm.models;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.c-id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m-content
     *
     * @mbg.generated
     */
    private String mContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m-reply
     *
     * @mbg.generated
     */
    private String mReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m-content-data
     *
     * @mbg.generated
     */
    private Date mContentData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m-reply-data
     *
     * @mbg.generated
     */
    private Date mReplyData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.userid
     *
     * @return the value of message.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.userid
     *
     * @param userid the value for message.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.c-id
     *
     * @return the value of message.c-id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.c-id
     *
     * @param cId the value for message.c-id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m-content
     *
     * @return the value of message.m-content
     *
     * @mbg.generated
     */
    public String getmContent() {
        return mContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m-content
     *
     * @param mContent the value for message.m-content
     *
     * @mbg.generated
     */
    public void setmContent(String mContent) {
        this.mContent = mContent == null ? null : mContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m-reply
     *
     * @return the value of message.m-reply
     *
     * @mbg.generated
     */
    public String getmReply() {
        return mReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m-reply
     *
     * @param mReply the value for message.m-reply
     *
     * @mbg.generated
     */
    public void setmReply(String mReply) {
        this.mReply = mReply == null ? null : mReply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m-content-data
     *
     * @return the value of message.m-content-data
     *
     * @mbg.generated
     */
    public Date getmContentData() {
        return mContentData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m-content-data
     *
     * @param mContentData the value for message.m-content-data
     *
     * @mbg.generated
     */
    public void setmContentData(Date mContentData) {
        this.mContentData = mContentData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m-reply-data
     *
     * @return the value of message.m-reply-data
     *
     * @mbg.generated
     */
    public Date getmReplyData() {
        return mReplyData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m-reply-data
     *
     * @param mReplyData the value for message.m-reply-data
     *
     * @mbg.generated
     */
    public void setmReplyData(Date mReplyData) {
        this.mReplyData = mReplyData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", cId=").append(cId);
        sb.append(", mContent=").append(mContent);
        sb.append(", mReply=").append(mReply);
        sb.append(", mContentData=").append(mContentData);
        sb.append(", mReplyData=").append(mReplyData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}