package com.trm.models;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-id
     *
     * @mbg.generated
     */
    private Integer oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-destination
     *
     * @mbg.generated
     */
    private String oDestination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-origin
     *
     * @mbg.generated
     */
    private String oOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-date
     *
     * @mbg.generated
     */
    private Date oDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-day
     *
     * @mbg.generated
     */
    private Integer oDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-people
     *
     * @mbg.generated
     */
    private Integer oPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-budget
     *
     * @mbg.generated
     */
    private Float oBudget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-explain
     *
     * @mbg.generated
     */
    private String oExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-type
     *
     * @mbg.generated
     */
    private String oType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.h-id
     *
     * @mbg.generated
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-id
     *
     * @return the value of order.o-id
     *
     * @mbg.generated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-id
     *
     * @param oId the value for order.o-id
     *
     * @mbg.generated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-destination
     *
     * @return the value of order.o-destination
     *
     * @mbg.generated
     */
    public String getoDestination() {
        return oDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-destination
     *
     * @param oDestination the value for order.o-destination
     *
     * @mbg.generated
     */
    public void setoDestination(String oDestination) {
        this.oDestination = oDestination == null ? null : oDestination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-origin
     *
     * @return the value of order.o-origin
     *
     * @mbg.generated
     */
    public String getoOrigin() {
        return oOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-origin
     *
     * @param oOrigin the value for order.o-origin
     *
     * @mbg.generated
     */
    public void setoOrigin(String oOrigin) {
        this.oOrigin = oOrigin == null ? null : oOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-date
     *
     * @return the value of order.o-date
     *
     * @mbg.generated
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-date
     *
     * @param oDate the value for order.o-date
     *
     * @mbg.generated
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-day
     *
     * @return the value of order.o-day
     *
     * @mbg.generated
     */
    public Integer getoDay() {
        return oDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-day
     *
     * @param oDay the value for order.o-day
     *
     * @mbg.generated
     */
    public void setoDay(Integer oDay) {
        this.oDay = oDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-people
     *
     * @return the value of order.o-people
     *
     * @mbg.generated
     */
    public Integer getoPeople() {
        return oPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-people
     *
     * @param oPeople the value for order.o-people
     *
     * @mbg.generated
     */
    public void setoPeople(Integer oPeople) {
        this.oPeople = oPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-budget
     *
     * @return the value of order.o-budget
     *
     * @mbg.generated
     */
    public Float getoBudget() {
        return oBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-budget
     *
     * @param oBudget the value for order.o-budget
     *
     * @mbg.generated
     */
    public void setoBudget(Float oBudget) {
        this.oBudget = oBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-explain
     *
     * @return the value of order.o-explain
     *
     * @mbg.generated
     */
    public String getoExplain() {
        return oExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-explain
     *
     * @param oExplain the value for order.o-explain
     *
     * @mbg.generated
     */
    public void setoExplain(String oExplain) {
        this.oExplain = oExplain == null ? null : oExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-type
     *
     * @return the value of order.o-type
     *
     * @mbg.generated
     */
    public String getoType() {
        return oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-type
     *
     * @param oType the value for order.o-type
     *
     * @mbg.generated
     */
    public void setoType(String oType) {
        this.oType = oType == null ? null : oType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.h-id
     *
     * @return the value of order.h-id
     *
     * @mbg.generated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.h-id
     *
     * @param hId the value for order.h-id
     *
     * @mbg.generated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oId=").append(oId);
        sb.append(", oDestination=").append(oDestination);
        sb.append(", oOrigin=").append(oOrigin);
        sb.append(", oDate=").append(oDate);
        sb.append(", oDay=").append(oDay);
        sb.append(", oPeople=").append(oPeople);
        sb.append(", oBudget=").append(oBudget);
        sb.append(", oExplain=").append(oExplain);
        sb.append(", oType=").append(oType);
        sb.append(", hId=").append(hId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}