package com.trm.models;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-id
     *
     * @mbg.generated
     */
    private Integer oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-title
     *
     * @mbg.generated
     */
    private String oTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-date
     *
     * @mbg.generated
     */
    private Date oDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-people
     *
     * @mbg.generated
     */
    private Integer oPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-price
     *
     * @mbg.generated
     */
    private Float oPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-explain
     *
     * @mbg.generated
     */
    private String oExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-name
     *
     * @mbg.generated
     */
    private String oName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o-phone
     *
     * @mbg.generated
     */
    private String oPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-id
     *
     * @return the value of order.o-id
     *
     * @mbg.generated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-id
     *
     * @param oId the value for order.o-id
     *
     * @mbg.generated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-title
     *
     * @return the value of order.o-title
     *
     * @mbg.generated
     */
    public String getoTitle() {
        return oTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-title
     *
     * @param oTitle the value for order.o-title
     *
     * @mbg.generated
     */
    public void setoTitle(String oTitle) {
        this.oTitle = oTitle == null ? null : oTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-date
     *
     * @return the value of order.o-date
     *
     * @mbg.generated
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-date
     *
     * @param oDate the value for order.o-date
     *
     * @mbg.generated
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-people
     *
     * @return the value of order.o-people
     *
     * @mbg.generated
     */
    public Integer getoPeople() {
        return oPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-people
     *
     * @param oPeople the value for order.o-people
     *
     * @mbg.generated
     */
    public void setoPeople(Integer oPeople) {
        this.oPeople = oPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-price
     *
     * @return the value of order.o-price
     *
     * @mbg.generated
     */
    public Float getoPrice() {
        return oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-price
     *
     * @param oPrice the value for order.o-price
     *
     * @mbg.generated
     */
    public void setoPrice(Float oPrice) {
        this.oPrice = oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-explain
     *
     * @return the value of order.o-explain
     *
     * @mbg.generated
     */
    public String getoExplain() {
        return oExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-explain
     *
     * @param oExplain the value for order.o-explain
     *
     * @mbg.generated
     */
    public void setoExplain(String oExplain) {
        this.oExplain = oExplain == null ? null : oExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-name
     *
     * @return the value of order.o-name
     *
     * @mbg.generated
     */
    public String getoName() {
        return oName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-name
     *
     * @param oName the value for order.o-name
     *
     * @mbg.generated
     */
    public void setoName(String oName) {
        this.oName = oName == null ? null : oName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o-phone
     *
     * @return the value of order.o-phone
     *
     * @mbg.generated
     */
    public String getoPhone() {
        return oPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o-phone
     *
     * @param oPhone the value for order.o-phone
     *
     * @mbg.generated
     */
    public void setoPhone(String oPhone) {
        this.oPhone = oPhone == null ? null : oPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oId=").append(oId);
        sb.append(", oTitle=").append(oTitle);
        sb.append(", oDate=").append(oDate);
        sb.append(", oPeople=").append(oPeople);
        sb.append(", oPrice=").append(oPrice);
        sb.append(", oExplain=").append(oExplain);
        sb.append(", oName=").append(oName);
        sb.append(", oPhone=").append(oPhone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}