package com.trm.models;

import java.io.Serializable;

public class Route implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r-id
     *
     * @mbg.generated
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r-region
     *
     * @mbg.generated
     */
    private String rRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r-oplace
     *
     * @mbg.generated
     */
    private String rOplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r-destination
     *
     * @mbg.generated
     */
    private String rDestination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.h-id
     *
     * @mbg.generated
     */
    private Integer hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r-tool
     *
     * @mbg.generated
     */
    private String rTool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r-id
     *
     * @return the value of route.r-id
     *
     * @mbg.generated
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r-id
     *
     * @param rId the value for route.r-id
     *
     * @mbg.generated
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r-region
     *
     * @return the value of route.r-region
     *
     * @mbg.generated
     */
    public String getrRegion() {
        return rRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r-region
     *
     * @param rRegion the value for route.r-region
     *
     * @mbg.generated
     */
    public void setrRegion(String rRegion) {
        this.rRegion = rRegion == null ? null : rRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r-oplace
     *
     * @return the value of route.r-oplace
     *
     * @mbg.generated
     */
    public String getrOplace() {
        return rOplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r-oplace
     *
     * @param rOplace the value for route.r-oplace
     *
     * @mbg.generated
     */
    public void setrOplace(String rOplace) {
        this.rOplace = rOplace == null ? null : rOplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r-destination
     *
     * @return the value of route.r-destination
     *
     * @mbg.generated
     */
    public String getrDestination() {
        return rDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r-destination
     *
     * @param rDestination the value for route.r-destination
     *
     * @mbg.generated
     */
    public void setrDestination(String rDestination) {
        this.rDestination = rDestination == null ? null : rDestination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.h-id
     *
     * @return the value of route.h-id
     *
     * @mbg.generated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.h-id
     *
     * @param hId the value for route.h-id
     *
     * @mbg.generated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r-tool
     *
     * @return the value of route.r-tool
     *
     * @mbg.generated
     */
    public String getrTool() {
        return rTool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r-tool
     *
     * @param rTool the value for route.r-tool
     *
     * @mbg.generated
     */
    public void setrTool(String rTool) {
        this.rTool = rTool == null ? null : rTool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rId=").append(rId);
        sb.append(", rRegion=").append(rRegion);
        sb.append(", rOplace=").append(rOplace);
        sb.append(", rDestination=").append(rDestination);
        sb.append(", hId=").append(hId);
        sb.append(", rTool=").append(rTool);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}