package com.trm.models;

import java.io.Serializable;

public class Spots implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-price
     *
     * @mbg.generated
     */
    private Integer sPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-days
     *
     * @mbg.generated
     */
    private Integer sDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-brief
     *
     * @mbg.generated
     */
    private String sBrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-type
     *
     * @mbg.generated
     */
    private String sType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-tool
     *
     * @mbg.generated
     */
    private String sTool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.s-img
     *
     * @mbg.generated
     */
    private String sImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spots.a-id
     *
     * @mbg.generated
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spots
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-id
     *
     * @return the value of spots.s-id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-id
     *
     * @param sId the value for spots.s-id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-name
     *
     * @return the value of spots.s-name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-name
     *
     * @param sName the value for spots.s-name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-price
     *
     * @return the value of spots.s-price
     *
     * @mbg.generated
     */
    public Integer getsPrice() {
        return sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-price
     *
     * @param sPrice the value for spots.s-price
     *
     * @mbg.generated
     */
    public void setsPrice(Integer sPrice) {
        this.sPrice = sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-days
     *
     * @return the value of spots.s-days
     *
     * @mbg.generated
     */
    public Integer getsDays() {
        return sDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-days
     *
     * @param sDays the value for spots.s-days
     *
     * @mbg.generated
     */
    public void setsDays(Integer sDays) {
        this.sDays = sDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-brief
     *
     * @return the value of spots.s-brief
     *
     * @mbg.generated
     */
    public String getsBrief() {
        return sBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-brief
     *
     * @param sBrief the value for spots.s-brief
     *
     * @mbg.generated
     */
    public void setsBrief(String sBrief) {
        this.sBrief = sBrief == null ? null : sBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-type
     *
     * @return the value of spots.s-type
     *
     * @mbg.generated
     */
    public String getsType() {
        return sType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-type
     *
     * @param sType the value for spots.s-type
     *
     * @mbg.generated
     */
    public void setsType(String sType) {
        this.sType = sType == null ? null : sType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-tool
     *
     * @return the value of spots.s-tool
     *
     * @mbg.generated
     */
    public String getsTool() {
        return sTool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-tool
     *
     * @param sTool the value for spots.s-tool
     *
     * @mbg.generated
     */
    public void setsTool(String sTool) {
        this.sTool = sTool == null ? null : sTool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.s-img
     *
     * @return the value of spots.s-img
     *
     * @mbg.generated
     */
    public String getsImg() {
        return sImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.s-img
     *
     * @param sImg the value for spots.s-img
     *
     * @mbg.generated
     */
    public void setsImg(String sImg) {
        this.sImg = sImg == null ? null : sImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spots.a-id
     *
     * @return the value of spots.a-id
     *
     * @mbg.generated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spots.a-id
     *
     * @param aId the value for spots.a-id
     *
     * @mbg.generated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spots
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sId=").append(sId);
        sb.append(", sName=").append(sName);
        sb.append(", sPrice=").append(sPrice);
        sb.append(", sDays=").append(sDays);
        sb.append(", sBrief=").append(sBrief);
        sb.append(", sType=").append(sType);
        sb.append(", sTool=").append(sTool);
        sb.append(", sImg=").append(sImg);
        sb.append(", aId=").append(aId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}