package com.trm.repositroy;

import com.trm.models.Hotel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated
     */
    Hotel selectByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated
     */
    List<Hotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hotel record);
}